
export const dummyUsers = [
  {
    firstname: "Chinedu",
    middlename: "Ifeanyi",
    lastname: "Okafor",
    email: "chinedu.okafor@example.com",
    phone: "08031234567",
    accountBalance: 245000.75,
    occupation: "Software Engineer",
    isAllowedToTransfer: true,
    income: 650000,
  },
  {
    firstname: "Amina",
    middlename: "Sadiya",
    lastname: "Yusuf",
    email: "amina.yusuf@example.com",
    phone: "08062345678",
    accountBalance: 18050.0,
    occupation: "Fashion Designer",
    isAllowedToTransfer: true,
    income: 220000,
  },
  {
    firstname: "Tunde",
    middlename: "Olawale",
    lastname: "Adebayo",
    email: "tunde.adebayo@example.com",
    phone: "08123456789",
    accountBalance: 905500.2,
    occupation: "Business Owner",
    isAllowedToTransfer: false,
    income: 1200000,
  },
  {
    firstname: "Blessing",
    middlename: "Chiamaka",
    lastname: "Eze",
    email: "blessing.eze@example.com",
    phone: "07011223344",
    accountBalance: 5600.35,
    occupation: "Student",
    isAllowedToTransfer: true,
    income: 45000,
  },
  {
    firstname: "Ibrahim",
    middlename: "Musa",
    lastname: "Suleiman",
    email: "ibrahim.suleiman@example.com",
    phone: "09055667788",
    accountBalance: 72450.0,
    occupation: "Civil Servant",
    isAllowedToTransfer: true,
    income: 180000,
  },
  {
    firstname: "Ngozi",
    middlename: "Nkiruka",
    lastname: "Umeh",
    email: "ngozi.umeh@example.com",
    phone: "08109876543",
    accountBalance: 3100000.0,
    occupation: "Doctor",
    isAllowedToTransfer: true,
    income: 2000000,
  },
  {
    firstname: "Samuel",
    middlename: "Oluwaseun",
    lastname: "Johnson",
    email: "samuel.johnson@example.com",
    phone: "07044556677",
    accountBalance: 450.0,
    occupation: "Ride-Hailing Driver",
    isAllowedToTransfer: false,
    income: 120000,
  },
  {
    firstname: "Khadijah",
    middlename: "Zainab",
    lastname: "Abdullahi",
    email: "khadijah.abdullahi@example.com",
    phone: "08077889900",
    accountBalance: 99500.99,
    occupation: "Teacher",
    isAllowedToTransfer: true,
    income: 160000,
  },
  {
    firstname: "Peter",
    middlename: "Chukwuemeka",
    lastname: "Nwosu",
    email: "peter.nwosu@example.com",
    phone: "08155667788",
    accountBalance: 65000.5,
    occupation: "Photographer",
    isAllowedToTransfer: true,
    income: 300000,
  },
  {
    firstname: "Hauwa",
    middlename: "Fatima",
    lastname: "Bello",
    email: "hauwa.bello@example.com",
    phone: "09011224455",
    accountBalance: 410250.0,
    occupation: "Bank Teller",
    isAllowedToTransfer: true,
    income: 250000,
  },
];
